# =====================================================
# CONFIGURACI\u00c3\u0093N DEL PROYECTO
# =====================================================
audio=input/audio/audio_base.wav
imagesFolder=input/images

fps=12
durationSeconds=10

# serial | parallel | both
mode=both

# cantidad de threads para el modo paralelo
threads=4

serialOutput=output/frames_serial
parallelOutput=output/frames_parallel

# Para FFmpeg
videoSerial=videoclip_serial.mp4
videoParallel=videoclip_parallel.mp4
